/**
 * Column definitions and enum options for Admin Data Management UI.
 */
export const ADMIN_ENTITY_MENU = [
  { slug: 'planning-orders', label: 'Planning Orders', icon: 'pi pi-list' },
  { slug: 'operations', label: 'Operations', icon: 'pi pi-cog' },
  { slug: 'components', label: 'Components', icon: 'pi pi-box' },
  { slug: 'materials', label: 'Materials', icon: 'pi pi-tag' },
  { slug: 'batches', label: 'Batches', icon: 'pi pi-database' },
  { slug: 'tric-cases', label: 'TRIC Cases', icon: 'pi pi-globe' },
  { slug: 'inspection-lots', label: 'Inspection Lots', icon: 'pi pi-check-square' },
  { slug: 'resources', label: 'Resources', icon: 'pi pi-users' },
  { slug: 'work-centers', label: 'Work Centers', icon: 'pi pi-sitemap' },
  { slug: 'packaging-lines', label: 'Packaging Lines', icon: 'pi pi-share-alt' },
  { slug: 'shift-calendars', label: 'Shift Calendars', icon: 'pi pi-calendar' },
  { slug: 'setup-matrix', label: 'Setup Matrix', icon: 'pi pi-sliders-h' },
  { slug: 'capacity-buckets', label: 'Capacity Buckets', icon: 'pi pi-chart-bar' },
  { slug: 'planning-horizons', label: 'Planning Horizons', icon: 'pi pi-clock' },
  { slug: 'exceptions', label: 'Exceptions', icon: 'pi pi-exclamation-triangle' },
  { slug: 'planning-results', label: 'Planning Results', icon: 'pi pi-file-export' },
];

export const ENUM_OPTIONS = {
  priority: ['HIGH', 'MEDIUM', 'LOW'],
  planningStatus: ['PLANNED', 'ROUGH', 'CONFIRMED', 'RELEASED'],
  componentType: ['BULK', 'PACKAGING', 'LABEL', 'INSERT'],
  qualityStatus: ['RELEASED', 'BLOCKED', 'QUARANTINE', 'PENDING'],
  tricStatus: ['APPROVED', 'BLOCKED', 'PENDING'],
  inspectionStatus: ['RELEASED', 'BLOCKED', 'PENDING', 'IN_INSPECTION'],
  resourceType: ['PERSON', 'EQUIPMENT', 'TOOL', 'LINE'],
  workCenterType: ['PROCESS', 'PACKAGING', 'QC'],
  shiftPattern: ['1_SHIFT', '2_SHIFT', '3_SHIFT'],
  exceptionStatus: ['OPEN', 'IN_REVIEW', 'RESOLVED', 'CLOSED'],
  severity: ['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'],
  scheduleType: ['LINE_SEQUENCING', 'DETAILED_SCHEDULING', 'OPERATIONS', 'WHAT_IF'],
  resultStatus: ['DRAFT', 'READY', 'CONFIRMED', 'SUPERSEDED'],
  colorFamily: ['Blue', 'Red', 'Yellow', 'Clear'],
  scopeType: ['MATERIAL', 'MATERIAL_GROUP', 'PRODUCT_FAMILY', 'PACKAGING_LINE', 'WORK_CENTER', 'PLANT', 'PLANNING_AREA'],
  horizonType: ['FROZEN', 'FIXED', 'FLEXIBLE', 'FORECAST'],
  plant: ['1000', '*'],
  planningArea: ['PACKAGING', 'BULK', 'PROCESS', '*'],
  material: ['DP-1000', 'DP-2000', 'DP-3000', 'DP-4000', 'DP-5000'],
  materialGroup: ['ALPHA_TABLET', 'BETA_CAPSULE', 'GAMMA_BLISTER', 'BULK_API', 'PACK_MAT'],
  productFamily: ['Tablet', 'Capsule', 'Blister', 'Liquid', 'Parenteral'],
  packagingLine: ['PACK_LINE_01', 'PACK_LINE_02', 'PACK_LINE_03', 'PACK_LINE_04', 'PACK_LINE_05'],
  workCenter: ['FILL_01', 'PK_01', 'PK_02', 'PACK_LINE_01', 'PACK_LINE_02', 'PACK_LINE_03'],
  scheduleHorizonType: ['FROZEN', 'FIXED', 'FLEXIBLE', 'FORECAST', 'OUT_OF_HORIZON'],
};

export const ENTITY_COLUMNS = {
  'planning-orders': {
    idField: 'orderId',
    columns: [
      { field: 'orderId', header: 'Order ID', required: true, sortable: true, filter: true },
      { field: 'plant', header: 'Plant', required: true, sortable: true, filter: true },
      { field: 'finishedGoodMaterial', header: 'Material', required: true, sortable: true, filter: true },
      { field: 'orderQuantity', header: 'Qty', type: 'number', required: true, sortable: true },
      { field: 'salesOrder', header: 'Sales Order', sortable: true },
      { field: 'destinationCountry', header: 'Country', sortable: true, filter: true },
      { field: 'priority', header: 'Priority', type: 'enum', enumKey: 'priority', sortable: true, filter: true },
      { field: 'plannedStartDate', header: 'Start', type: 'date', sortable: true },
      { field: 'plannedEndDate', header: 'End', type: 'date', sortable: true },
      { field: 'productionLine', header: 'Line', sortable: true, filter: true },
      { field: 'planningStatus', header: 'Status', type: 'enum', enumKey: 'planningStatus', filter: true },
    ],
  },
  operations: {
    idField: 'operationId',
    columns: [
      { field: 'operationId', header: 'Operation ID', required: true, sortable: true },
      { field: 'orderId', header: 'Order', required: true, sortable: true, filter: true },
      { field: 'operationNo', header: 'Op No', type: 'number', required: true, sortable: true },
      { field: 'operationName', header: 'Name', sortable: true },
      { field: 'workCenterId', header: 'Work Center', required: true, filter: true },
      { field: 'setupTimeMinutes', header: 'Setup (min)', type: 'number', sortable: true },
      { field: 'runTimeMinutes', header: 'Run (min)', type: 'number', sortable: true },
      { field: 'teardownTimeMinutes', header: 'Teardown (min)', type: 'number', sortable: true },
      { field: 'cleaningTimeMinutes', header: 'Cleaning (min)', type: 'number', sortable: true },
      { field: 'isBottleneck', header: 'Bottleneck', type: 'boolean', sortable: true },
      { field: 'plannedStartDate', header: 'Start', type: 'date' },
      { field: 'plannedEndDate', header: 'End', type: 'date' },
    ],
  },
  components: {
    idField: 'componentId',
    columns: [
      { field: 'componentId', header: 'Component ID', required: true },
      { field: 'orderId', header: 'Order', required: true, filter: true },
      { field: 'materialNumber', header: 'Material', required: true, filter: true },
      { field: 'componentType', header: 'Type', type: 'enum', enumKey: 'componentType', filter: true },
      { field: 'requiredQuantity', header: 'Required', type: 'number', required: true },
      { field: 'availableQuantity', header: 'Available', type: 'number' },
      { field: 'unit', header: 'Unit' },
    ],
  },
  materials: {
    idField: 'materialNumber',
    columns: [
      { field: 'materialNumber', header: 'Material', required: true, sortable: true },
      { field: 'materialDescription', header: 'Description', sortable: true },
      { field: 'packageType', header: 'Package', sortable: true },
      { field: 'campaignGroup', header: 'Campaign', sortable: true, filter: true },
      { field: 'colorFamily', header: 'Color', type: 'enum', enumKey: 'colorFamily', filter: true },
      { field: 'revenuePerUnit', header: 'Revenue/Unit', type: 'number' },
      { field: 'regulatoryCritical', header: 'Regulatory', type: 'boolean' },
    ],
  },
  batches: {
    idField: 'batchId',
    columns: [
      { field: 'batchId', header: 'Batch ID', required: true, sortable: true },
      { field: 'batchNumber', header: 'Batch No', sortable: true },
      { field: 'materialNumber', header: 'Material', required: true, filter: true },
      { field: 'availableQuantity', header: 'Available', type: 'number', required: true, sortable: true },
      { field: 'quantity', header: 'Total Qty', type: 'number' },
      { field: 'remainingShelfLifePercent', header: 'RMSL %', type: 'number' },
      { field: 'qualityStatus', header: 'QA Status', type: 'enum', enumKey: 'qualityStatus', filter: true },
      { field: 'expiryDate', header: 'Expiry', type: 'date', sortable: true },
      { field: 'plant', header: 'Plant', filter: true },
    ],
  },
  'tric-cases': {
    idField: 'tricCaseId',
    columns: [
      { field: 'tricCaseId', header: 'TRIC Case ID', required: true },
      { field: 'batchNumber', header: 'Batch', required: true, filter: true },
      { field: 'country', header: 'Country', required: true, filter: true },
      { field: 'materialNumber', header: 'Material', filter: true },
      { field: 'status', header: 'Status', type: 'enum', enumKey: 'tricStatus', required: true, filter: true },
      { field: 'validFrom', header: 'Valid From', type: 'date' },
      { field: 'validTo', header: 'Valid To', type: 'date' },
      { field: 'notes', header: 'Notes' },
    ],
  },
  'inspection-lots': {
    idField: 'lotId',
    columns: [
      { field: 'lotId', header: 'Lot ID', required: true },
      { field: 'batchId', header: 'Batch', required: true, filter: true },
      { field: 'materialNumber', header: 'Material', required: true },
      { field: 'status', header: 'Status', type: 'enum', enumKey: 'inspectionStatus', filter: true },
      { field: 'usageDecision', header: 'Usage Decision' },
      { field: 'createdDate', header: 'Created', type: 'date' },
      { field: 'releaseDate', header: 'Released', type: 'date' },
    ],
  },
  resources: {
    idField: 'resourceId',
    columns: [
      { field: 'resourceId', header: 'Resource ID', required: true },
      { field: 'resourceName', header: 'Name', required: true, sortable: true },
      { field: 'resourceType', header: 'Type', type: 'enum', enumKey: 'resourceType', filter: true },
      { field: 'plant', header: 'Plant', filter: true },
      { field: 'capacityHoursPerDay', header: 'Hours/Day', type: 'number' },
      { field: 'active', header: 'Active', type: 'boolean' },
    ],
  },
  'work-centers': {
    idField: 'workCenterId',
    columns: [
      { field: 'workCenterId', header: 'WC ID', required: true, sortable: true },
      { field: 'workCenterName', header: 'Name', sortable: true },
      { field: 'plantId', header: 'Plant', filter: true },
      { field: 'type', header: 'Type', type: 'enum', enumKey: 'workCenterType', filter: true },
      { field: 'isBottleneck', header: 'Bottleneck', type: 'boolean', sortable: true },
      { field: 'capacityHoursPerDay', header: 'Hrs/Day', type: 'number' },
      { field: 'capacityUnitsPerDay', header: 'Units/Day', type: 'number' },
      { field: 'performanceFactor', header: 'Perf. Factor', type: 'number' },
      { field: 'active', header: 'Active', type: 'boolean' },
    ],
  },
  'packaging-lines': {
    idField: 'lineId',
    columns: [
      { field: 'lineId', header: 'Line ID', required: true, sortable: true },
      { field: 'lineName', header: 'Name', sortable: true },
      { field: 'plantId', header: 'Plant', filter: true },
      { field: 'capacityUnitsPerDay', header: 'Units/Day', type: 'number', sortable: true },
      { field: 'shiftPattern', header: 'Shifts', type: 'enum', enumKey: 'shiftPattern' },
      { field: 'performanceFactor', header: 'Perf. Factor', type: 'number' },
      { field: 'active', header: 'Active', type: 'boolean' },
    ],
  },
  'shift-calendars': {
    idField: '_compositeId',
    columns: [
      { field: 'lineId', header: 'Line', required: true, filter: true, sortable: true },
      { field: 'weekStarting', header: 'Week Start', required: true, type: 'date', sortable: true },
      { field: 'availableHours', header: 'Avail. Hours', type: 'number', sortable: true },
      { field: 'maxUnitsPerDay', header: 'Max Units/Day', type: 'number' },
    ],
  },
  'setup-matrix': {
    idField: '_compositeId',
    columns: [
      { field: 'fromColor', header: 'From Color', required: true, type: 'enum', enumKey: 'colorFamily', filter: true },
      { field: 'toColor', header: 'To Color', required: true, type: 'enum', enumKey: 'colorFamily', filter: true },
      { field: 'setupMinutes', header: 'Setup (min)', type: 'number', required: true, sortable: true },
      { field: 'description', header: 'Description' },
    ],
  },
  'capacity-buckets': {
    idField: 'bucketId',
    columns: [
      { field: 'bucketId', header: 'Bucket ID', required: true },
      { field: 'plantId', header: 'Plant', filter: true },
      { field: 'lineId', header: 'Line', filter: true },
      { field: 'weekStarting', header: 'Week', type: 'date', sortable: true },
      { field: 'totalCapacity', header: 'Total', type: 'number', sortable: true },
      { field: 'allocatedCapacity', header: 'Allocated', type: 'number' },
      { field: 'remainingCapacity', header: 'Remaining', type: 'number' },
      { field: 'utilizationPercent', header: 'Util %', type: 'number', sortable: true },
    ],
  },
  exceptions: {
    idField: 'exceptionId',
    columns: [
      { field: 'exceptionId', header: 'Exception ID', required: true },
      { field: 'type', header: 'Type', filter: true, sortable: true },
      { field: 'packagingOrderId', header: 'Order', filter: true },
      { field: 'status', header: 'Status', type: 'enum', enumKey: 'exceptionStatus', filter: true },
      { field: 'severity', header: 'Severity', type: 'enum', enumKey: 'severity', filter: true },
      { field: 'message', header: 'Message' },
      { field: 'createdAt', header: 'Created', type: 'date', sortable: true },
    ],
  },
  'planning-results': {
    idField: 'resultId',
    columns: [
      { field: 'resultId', header: 'Result ID', required: true },
      { field: 'scheduleType', header: 'Type', type: 'enum', enumKey: 'scheduleType', filter: true },
      { field: 'label', header: 'Label', sortable: true },
      { field: 'status', header: 'Status', type: 'enum', enumKey: 'resultStatus', filter: true },
      { field: 'itemCount', header: 'Items', type: 'number', sortable: true },
      { field: 'applicablePlanningHorizon', header: 'Horizon ID', filter: true },
      { field: 'horizonType', header: 'Horizon Type', type: 'enum', enumKey: 'scheduleHorizonType', filter: true },
      { field: 'horizonViolation', header: 'Violation', type: 'boolean' },
      { field: 'reschedulingAllowed', header: 'Reschedule OK', type: 'boolean' },
      { field: 'optimizationAllowed', header: 'Optimize OK', type: 'boolean' },
      { field: 'createdAt', header: 'Created', type: 'date', sortable: true },
      { field: 'kpisSummary', header: 'KPI Summary' },
    ],
  },
  'planning-horizons': {
    idField: 'horizonId',
    columns: [
      { field: 'horizonId', header: 'Horizon ID', required: true, sortable: true },
      { field: 'horizonName', header: 'Name', required: true, sortable: true },
      { field: 'plant', header: 'Plant', type: 'enum', enumKey: 'plant', required: true, filter: true },
      { field: 'planningArea', header: 'Planning Area', type: 'enum', enumKey: 'planningArea', required: true, filter: true },
      { field: 'scopeType', header: 'Scope Type', type: 'enum', enumKey: 'scopeType', required: true, filter: true, sortable: true },
      { field: 'scopeValue', header: 'Scope Value', required: true, filter: true },
      { field: 'horizonType', header: 'Horizon Type', type: 'enum', enumKey: 'horizonType', required: true, filter: true, sortable: true },
      { field: 'startOffsetDays', header: 'Start (T+)', type: 'number', required: true, sortable: true },
      { field: 'endOffsetDays', header: 'End (T+)', type: 'number', required: true, sortable: true },
      { field: 'isEditable', header: 'Editable', type: 'boolean' },
      { field: 'isAutoSchedulable', header: 'Auto Schedule', type: 'boolean' },
      { field: 'allowRescheduling', header: 'Allow Reschedule', type: 'boolean' },
      { field: 'priority', header: 'Priority', type: 'number', sortable: true },
      { field: 'validFrom', header: 'Valid From', type: 'date' },
      { field: 'validTo', header: 'Valid To', type: 'date' },
      { field: 'description', header: 'Description' },
    ],
  },
};

export function getEntityConfig(slug) {
  return ENTITY_COLUMNS[slug] || null;
}
